# Generated by Django 4.2.9 on 2024-02-15 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('wmo_id', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_date_time_full', models.IntegerField(blank=True, default=None, null=True)),
                ('air_temp', models.FloatField(blank=True, default=None, max_length=255, null=True)),
                ('dewpt', models.FloatField(blank=True, default=None, max_length=255, null=True)),
                ('wind_dir', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('wind_spd_kmh', models.IntegerField(blank=True, default=None, null=True)),
                ('wmo', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='woe.source')),
            ],
        ),
    ]
