# Generated by Django 4.2.9 on 2024-02-01 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, default=None, null=True)),
                ('wmo', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('history_product', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('local_date_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('local_date_time_full', models.IntegerField(blank=True, default=None, null=True)),
                ('aifstime_utc', models.IntegerField(blank=True, default=None, null=True)),
                ('lat', models.FloatField(blank=True, default=None, max_length=255, null=True)),
                ('lon', models.FloatField(blank=True, default=None, max_length=255, null=True)),
                ('apparent_t', models.FloatField(blank=True, default=None, max_length=255, null=True)),
                ('cloud', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('cloud_base_m', models.IntegerField(blank=True, default=None, null=True)),
                ('cloud_oktas', models.IntegerField(blank=True, default=None, null=True)),
                ('cloud_type_id', models.IntegerField(blank=True, default=None, null=True)),
                ('cloud_type', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('delta_t', models.FloatField(blank=True, default=None, max_length=255, null=True)),
                ('gust_kmh', models.IntegerField(blank=True, default=None, null=True)),
                ('gust_kt', models.IntegerField(blank=True, default=None, null=True)),
                ('air_temp', models.FloatField(blank=True, default=None, max_length=255, null=True)),
                ('dewpt', models.FloatField(blank=True, default=None, max_length=255, null=True)),
                ('press', models.FloatField(blank=True, default=None, max_length=255, null=True)),
                ('press_qnh', models.FloatField(blank=True, default=None, max_length=255, null=True)),
                ('press_msl', models.FloatField(blank=True, default=None, max_length=255, null=True)),
                ('press_tend', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('rain_trace', models.FloatField(blank=True, default=None, max_length=255, null=True)),
                ('rel_hum', models.IntegerField(blank=True, default=None, null=True)),
                ('sea_state', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('swell_dir_worded', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('swell_height', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('swell_period', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('vis_km', models.IntegerField(blank=True, default=None, null=True)),
                ('weather', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('wind_dir', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('wind_spd_kmh', models.IntegerField(blank=True, default=None, null=True)),
                ('wind_spd_kt', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('wmo_id', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
            ],
        ),
    ]
