# Generated by Django 4.2.9 on 2024-01-31 03:06
import csv
from django.db import migrations, models
import os

_source = apps.get_model("woe", "Source")
 _observation = apps.get_model("woe", "Observation")
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

def populate_observations(apps, schema_editor):
    for value in [2,6,3,5]:
        obs = _observation()
        obs.location = _source(value)
        obs.save()
        

def populate_sources(apps, schema_editor):
    with open(os.path.join(BASE_DIR, '../../data/Source.csv')) as csvfile:
        reader = csv.reader(csvfile, delimiter=',', quotechar='"')
        for line in reader:
            source = _source()
            source.name = line[0]
            source.wmo_id = line[1]
            source.url = line[2]
            source.save()


class Migration(migrations.Migration):

    dependencies = [
        ('woe', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_sources),
        migrations.RunPython(populate_observations)
    ]
