# Generated by Django 4.2.9 on 2024-02-01 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('woe', '0004_auto_20240131_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='wmo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='woe.source'),
        ),
    ]
